/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package harvard.fp.data;

import harvard.fp.data.generator.JsonDataSetGenerator;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        JsonDataSetGenerator dataGenerator = new JsonDataSetGenerator();
        dataGenerator.generateData();
    }
}
