/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package harvard.fp.data;

import harvard.fp.data.generator.JsonDataSetGenerator;
import harvard.fp.data.generator.KafkaDataGenerator;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        KafkaDataGenerator dataGenerator = new KafkaDataGenerator();
        dataGenerator.generateData();
    }
}
